version: "3.7"

networks:
  votes:

services:
  db:
    image: mongo:latest
    networks:
      - votes
    environment:
      MONGO_INITDB_ROOT_USERNAME: votes
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: votes

  votes-backend:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    environment:
      DATABASE_URI: mongodb://votes:secret@db
      AUTH_URL: http://localhost:8000/mock-auth/token-response
      DATABASE: votes
    volumes:
      - "../..:/app"
      - "votes-web-packages:/usr/local/lib/python3.8/site-packages"
      - "votes-web-bin:/usr/local/bin"
    ports:
      - "8000:8000"          
    working_dir: /app
    command: "/app/docker/development/run-service.sh"
    networks:
      - votes
    depends_on:
      - db

volumes:
  votes-web-packages:
  votes-web-bin:
  db:
